// <auto-generated />
using System;
using Building_Permits.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Building_Permits.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250909232236_current")]
    partial class current
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Building_Permits.Core.Entities.ArchivedPermit", b =>
                {
                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("PermitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable((string)null);

                    b.ToView("ArchivedPermits", (string)null);
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PermitId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PermitId")
                        .IsUnique()
                        .HasFilter("[PermitId] IS NOT NULL");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AgreementAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PermitId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReceivedAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("RemainingAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 2)")
                        .HasComputedColumnSql("([AgreementAmount]-[ReceivedAmount])", true);

                    b.HasKey("Id");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PermitId")
                        .HasColumnType("int");

                    b.Property<int?>("PermitStageId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PermitId");

                    b.HasIndex("PermitStageId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Permit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Current_Execution_Stage")
                        .HasColumnType("int");

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<string>("PermitType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId")
                        .IsUnique()
                        .HasFilter("[ExpenseId] IS NOT NULL");

                    b.ToTable("Permits", (string)null);
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.PermitStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermitId")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TransactionNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Transaction_Number");

                    b.HasKey("Id");

                    b.HasIndex("PermitId");

                    b.HasIndex("StageId");

                    b.ToTable("PermitStages", (string)null);
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultDaysLimit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Client", b =>
                {
                    b.HasOne("Building_Permits.Core.Entities.Permit", "Permit")
                        .WithOne("Client")
                        .HasForeignKey("Building_Permits.Core.Entities.Client", "PermitId");

                    b.Navigation("Permit");
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Notification", b =>
                {
                    b.HasOne("Building_Permits.Core.Entities.Permit", "Permit")
                        .WithMany("Notifications")
                        .HasForeignKey("PermitId");

                    b.HasOne("Building_Permits.Core.Entities.PermitStage", "PermitStage")
                        .WithMany("Notifications")
                        .HasForeignKey("PermitStageId");

                    b.Navigation("Permit");

                    b.Navigation("PermitStage");
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Permit", b =>
                {
                    b.HasOne("Building_Permits.Core.Entities.Expense", "Expense")
                        .WithOne("Permit")
                        .HasForeignKey("Building_Permits.Core.Entities.Permit", "ExpenseId");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.PermitStage", b =>
                {
                    b.HasOne("Building_Permits.Core.Entities.Permit", "Permit")
                        .WithMany("PermitStages")
                        .HasForeignKey("PermitId")
                        .IsRequired();

                    b.HasOne("Building_Permits.Core.Entities.Stage", "Stage")
                        .WithMany("PermitStages")
                        .HasForeignKey("StageId")
                        .IsRequired();

                    b.Navigation("Permit");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Expense", b =>
                {
                    b.Navigation("Permit")
                        .IsRequired();
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Permit", b =>
                {
                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("PermitStages");
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.PermitStage", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Building_Permits.Core.Entities.Stage", b =>
                {
                    b.Navigation("PermitStages");
                });
#pragma warning restore 612, 618
        }
    }
}
